## One-dimensional tensors

In [57]:
import tensorflow as tf 
import numpy as np

In [58]:
tenso1D = np.array([1.3 , 1 , 5 , 32.7]) #,np.float64)
print(tenso1D.dtype)


float64


In [59]:
print(tenso1D)

[  1.3   1.    5.   32.7]


In [60]:
#passar para tensorflow 

In [61]:
c_tensor = tf.convert_to_tensor(tenso1D , dtype = tf.float64)


In [62]:
with tf.Session() as sess:
    print(sess.run(c_tensor))
    print(sess.run(c_tensor[0]))
    print(sess.run(c_tensor[3]))

[  1.3   1.    5.   32.7]
1.3
32.7


## Two-dimensional tensors

In [63]:
import numpy as np
import tensorflow as tf

In [64]:
tensor_2d = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

In [65]:
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [66]:
#build two integer  3x3

In [71]:
# numpy python 
matrix1 = np.array([[2,2,2],[2,2,2],[2,2,2]] , dtype='int32')
matrix2 = np.array([[1,1,1],[1,1,1],[1,1,1]],dtype='int32')

matrix_3 = np.array([[2,7,2],[1,4,2],[9,0,2]] , dtype='float32')

In [74]:
m1 = tf.constant(matrix1)
m2 = tf.constant(matrix2)

#produto m1 X m2

m_produc  = tf.matmul(m1 , m1)
m_add     = tf.add(m1 , m2)
m_det     = tf.matrix_determinant(matrix_3)    


In [77]:
with tf.Session() as s:
    print(s.run(m_produc))
    print('\n\n')
    print(s.run(m_add))
    print('det',s.run(m_det))

[[12 12 12]
 [12 12 12]
 [12 12 12]]



[[3 3 3]
 [3 3 3]
 [3 3 3]]
det 56.0


## Three-dimensional tensors

In [78]:
import tensorflow as tf
import numpy as np

In [81]:
tensor_3D  = np.array([[[1,2],[3,4]] , [[5,6], [7,8]]])

In [83]:
print(tensor_3D.shape)

(2, 2, 2)
